apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-housing-deployment
  labels:
    app: api-housing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-housing
  template:
    metadata:
      labels:
        app: api-housing
    spec:
      containers:
      - name: api-housing-container
        image: api-california-housing:1.0
        ports:
        - containerPort: 5000
