apiVersion: v1
kind: Service
metadata:
  name: api-housing-service
spec:
  type: NodePort
  selector:
    app: api-housing
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
